github_json = [
  {
    "id": 266204894,
    "name": "nextbox-ui-plugin",
    "full_name": "/iDebugAll/nextbox-ui-plugin",
    "owner": {
      "login": "iDebugAll",
      "id": 32979193,
      "url": "https://github.com/iDebugAll",
      "type": "User"
    },
    "url": "https://github.com/iDebugAll/nextbox-ui-plugin",
    "description": "A topology visualization plugin for Netbox powered by NextUI Toolkit",
    "git_url": "git://github.com/iDebugAll/nextbox-ui-plugin.git",
    "clone_url": "https://github.com/iDebugAll/nextbox-ui-plugin.git",
    "created_at": "2020-05-22T20:50:09Z",
    "updated_at": "2022-03-14T18:30:50Z",
    "pushed_at": "2022-01-17T13:29:15Z",
    "stargazers_count": 289,
    "watchers_count": 289,
    "language": "Python",
    "forks": 35,
    "open_issues": 40,
    "topics": [
      "netbox",
      "netbox-docker",
      "netbox-plugin",
      "nextui",
      "topology-visualization"
    ]
  },
  {
    "id": 252408164,
    "name": "netbox-topology-views",
    "full_name": "/mattieserver/netbox-topology-views",
    "owner": {
      "login": "mattieserver",
      "id": 3049868,
      "url": "https://github.com/mattieserver",
      "type": "User"
    },
    "url": "https://github.com/mattieserver/netbox-topology-views",
    "description": "A netbox plugin that draws topology views ",
    "git_url": "git://github.com/mattieserver/netbox-topology-views.git",
    "clone_url": "https://github.com/mattieserver/netbox-topology-views.git",
    "created_at": "2020-04-02T09:14:29Z",
    "updated_at": "2022-03-13T16:43:23Z",
    "pushed_at": "2022-03-10T10:50:06Z",
    "stargazers_count": 200,
    "watchers_count": 200,
    "language": "Python",
    "forks": 15,
    "open_issues": 25,
    "topics": ["netbox", "netbox-plugin"]
  },
  {
    "id": 263155871,
    "name": "ntc-netbox-plugin-onboarding",
    "full_name": "/networktocode/ntc-netbox-plugin-onboarding",
    "owner": {
      "login": "networktocode",
      "id": 13106404,
      "url": "https://github.com/networktocode",
      "type": "Organization"
    },
    "url": "https://github.com/networktocode/ntc-netbox-plugin-onboarding",
    "description": "A plugin for NetBox to easily onboard new devices.",
    "git_url": "git://github.com/networktocode/ntc-netbox-plugin-onboarding.git",
    "clone_url": "https://github.com/networktocode/ntc-netbox-plugin-onboarding.git",
    "created_at": "2020-05-11T20:53:35Z",
    "updated_at": "2022-03-14T18:42:12Z",
    "pushed_at": "2021-12-13T20:59:53Z",
    "stargazers_count": 175,
    "watchers_count": 175,
    "language": "Python",
    "forks": 35,
    "open_issues": 15,
    "topics": ["napalm", "netbox", "netbox-plugin", "netmiko", "network"]
  },
  {
    "id": 355556201,
    "name": "netbox-bgp",
    "full_name": "/k01ek/netbox-bgp",
    "owner": {
      "login": "k01ek",
      "id": 33313888,
      "url": "https://github.com/k01ek",
      "type": "User"
    },
    "url": "https://github.com/k01ek/netbox-bgp",
    "description": "NetBox plugin for BGP related objects documentation",
    "git_url": "git://github.com/k01ek/netbox-bgp.git",
    "clone_url": "https://github.com/k01ek/netbox-bgp.git",
    "created_at": "2021-04-07T13:30:46Z",
    "updated_at": "2022-03-11T22:12:55Z",
    "pushed_at": "2022-02-24T20:36:24Z",
    "stargazers_count": 83,
    "watchers_count": 83,
    "language": "Python",
    "forks": 16,
    "open_issues": 14,
    "topics": ["bgp", "netbox", "netbox-plugin"]
  },
  {
    "id": 394589389,
    "name": "netbox-dns",
    "full_name": "/auroraresearchlab/netbox-dns",
    "owner": {
      "login": "auroraresearchlab",
      "id": 84396868,
      "url": "https://github.com/auroraresearchlab",
      "type": "Organization"
    },
    "url": "https://github.com/auroraresearchlab/netbox-dns",
    "description": "Netbox Dns is a netbox plugin for managing zone, nameserver and record inventory.",
    "git_url": "git://github.com/auroraresearchlab/netbox-dns.git",
    "clone_url": "https://github.com/auroraresearchlab/netbox-dns.git",
    "created_at": "2021-08-10T09:04:03Z",
    "updated_at": "2022-03-10T20:14:27Z",
    "pushed_at": "2022-03-08T17:55:09Z",
    "stargazers_count": 80,
    "watchers_count": 80,
    "language": "Python",
    "forks": 11,
    "open_issues": 11,
    "topics": ["dns", "netbox", "netbox-plugin"]
  },
  {
    "id": 266182368,
    "name": "netbox-plugin-auth-saml2",
    "full_name": "/jeremyschulman/netbox-plugin-auth-saml2",
    "owner": {
      "login": "jeremyschulman",
      "id": 2607956,
      "url": "https://github.com/jeremyschulman",
      "type": "User"
    },
    "url": "https://github.com/jeremyschulman/netbox-plugin-auth-saml2",
    "description": "Netbox plugin for SSO using SAML2",
    "git_url": "git://github.com/jeremyschulman/netbox-plugin-auth-saml2.git",
    "clone_url": "https://github.com/jeremyschulman/netbox-plugin-auth-saml2.git",
    "created_at": "2020-05-22T18:37:41Z",
    "updated_at": "2022-03-10T17:07:41Z",
    "pushed_at": "2021-12-11T14:25:17Z",
    "stargazers_count": 78,
    "watchers_count": 78,
    "language": "Python",
    "forks": 14,
    "open_issues": 9,
    "topics": ["netbox-plugin"]
  },
  {
    "id": 255748869,
    "name": "netbox-ddns",
    "full_name": "/sjm-steffann/netbox-ddns",
    "owner": {
      "login": "sjm-steffann",
      "id": 13750942,
      "url": "https://github.com/sjm-steffann",
      "type": "Organization"
    },
    "url": "https://github.com/sjm-steffann/netbox-ddns",
    "description": "Dynamic DNS Connector for NetBox",
    "git_url": "git://github.com/sjm-steffann/netbox-ddns.git",
    "clone_url": "https://github.com/sjm-steffann/netbox-ddns.git",
    "created_at": "2020-04-14T23:09:41Z",
    "updated_at": "2022-03-11T21:57:25Z",
    "pushed_at": "2022-02-11T16:52:34Z",
    "stargazers_count": 59,
    "watchers_count": 59,
    "language": "Python",
    "forks": 7,
    "open_issues": 3,
    "topics": ["dns", "dns-updates", "netbox", "netbox-plugin"]
  },
  {
    "id": 279843568,
    "name": "netbox-qrcode",
    "full_name": "/k01ek/netbox-qrcode",
    "owner": {
      "login": "k01ek",
      "id": 33313888,
      "url": "https://github.com/k01ek",
      "type": "User"
    },
    "url": "https://github.com/k01ek/netbox-qrcode",
    "description": "NetBox Plugin for generate QR Codes",
    "git_url": "git://github.com/k01ek/netbox-qrcode.git",
    "clone_url": "https://github.com/k01ek/netbox-qrcode.git",
    "created_at": "2020-07-15T10:56:58Z",
    "updated_at": "2022-03-12T08:42:05Z",
    "pushed_at": "2021-10-13T08:02:36Z",
    "stargazers_count": 58,
    "watchers_count": 58,
    "language": "Python",
    "forks": 10,
    "open_issues": 5,
    "topics": ["netbox", "netbox-plugin"]
  },
  {
    "id": 341549669,
    "name": "netbox-plugin-config-officer",
    "full_name": "/artyomovs/netbox-plugin-config-officer",
    "owner": {
      "login": "artyomovs",
      "id": 4401664,
      "url": "https://github.com/artyomovs",
      "type": "User"
    },
    "url": "https://github.com/artyomovs/netbox-plugin-config-officer",
    "description": "NetBox plugin that stores configuration diffs and checks templates compliance",
    "git_url": "git://github.com/artyomovs/netbox-plugin-config-officer.git",
    "clone_url": "https://github.com/artyomovs/netbox-plugin-config-officer.git",
    "created_at": "2021-02-23T12:36:40Z",
    "updated_at": "2022-03-12T19:02:28Z",
    "pushed_at": "2021-10-12T07:12:08Z",
    "stargazers_count": 56,
    "watchers_count": 56,
    "language": "Python",
    "forks": 5,
    "open_issues": 4,
    "topics": ["netbox-plugin"]
  },
  {
    "id": 355673550,
    "name": "netbox-proxbox",
    "full_name": "/N-Multifibra/netbox-proxbox",
    "owner": {
      "login": "N-Multifibra",
      "id": 69046483,
      "url": "https://github.com/N-Multifibra",
      "type": "Organization"
    },
    "url": "https://github.com/N-Multifibra/netbox-proxbox",
    "description": "Netbox Plugin for integration between Proxmox and Netbox",
    "git_url": "git://github.com/N-Multifibra/netbox-proxbox.git",
    "clone_url": "https://github.com/N-Multifibra/netbox-proxbox.git",
    "created_at": "2021-04-07T20:26:30Z",
    "updated_at": "2022-03-14T18:13:57Z",
    "pushed_at": "2022-03-12T15:21:08Z",
    "stargazers_count": 44,
    "watchers_count": 44,
    "language": "Python",
    "forks": 11,
    "open_issues": 17,
    "topics": ["netbox", "netbox-plugin", "proxmox", "proxmoxer", "pynetbox"]
  },
  {
    "id": 261046046,
    "name": "netbox-virtual-circuit-plugin",
    "full_name": "/vapor-ware/netbox-virtual-circuit-plugin",
    "owner": {
      "login": "vapor-ware",
      "id": 11537827,
      "url": "https://github.com/vapor-ware",
      "type": "Organization"
    },
    "url": "https://github.com/vapor-ware/netbox-virtual-circuit-plugin",
    "description": "A plugin for NetBox that supports Virtual Circuit management",
    "git_url": "git://github.com/vapor-ware/netbox-virtual-circuit-plugin.git",
    "clone_url": "https://github.com/vapor-ware/netbox-virtual-circuit-plugin.git",
    "created_at": "2020-05-04T00:14:53Z",
    "updated_at": "2022-03-04T01:19:33Z",
    "pushed_at": "2022-02-08T16:24:28Z",
    "stargazers_count": 40,
    "watchers_count": 40,
    "language": "Python",
    "forks": 18,
    "open_issues": 8,
    "topics": ["netbox", "netbox-plugin"]
  },
  {
    "id": 336859408,
    "name": "phonebox_plugin",
    "full_name": "/iDebugAll/phonebox_plugin",
    "owner": {
      "login": "iDebugAll",
      "id": 32979193,
      "url": "https://github.com/iDebugAll",
      "type": "User"
    },
    "url": "https://github.com/iDebugAll/phonebox_plugin",
    "description": "A Telephone Number Management Plugin for Netbox and more",
    "git_url": "git://github.com/iDebugAll/phonebox_plugin.git",
    "clone_url": "https://github.com/iDebugAll/phonebox_plugin.git",
    "created_at": "2021-02-07T18:29:01Z",
    "updated_at": "2022-03-07T16:09:28Z",
    "pushed_at": "2022-02-09T07:30:02Z",
    "stargazers_count": 39,
    "watchers_count": 39,
    "language": "HTML",
    "forks": 10,
    "open_issues": 8,
    "topics": ["netbox-plugin", "telephonymanager", "voip"]
  },
  {
    "id": 345412325,
    "name": "netbox-secretstore",
    "full_name": "/DanSheps/netbox-secretstore",
    "owner": {
      "login": "DanSheps",
      "id": 11049792,
      "url": "https://github.com/DanSheps",
      "type": "User"
    },
    "url": "https://github.com/DanSheps/netbox-secretstore",
    "description": "null",
    "git_url": "git://github.com/DanSheps/netbox-secretstore.git",
    "clone_url": "https://github.com/DanSheps/netbox-secretstore.git",
    "created_at": "2021-03-07T17:42:13Z",
    "updated_at": "2022-03-11T17:54:45Z",
    "pushed_at": "2022-01-04T16:08:30Z",
    "stargazers_count": 34,
    "watchers_count": 34,
    "language": "Python",
    "forks": 10,
    "open_issues": 3,
    "topics": ["netbox-plugin"]
  },
  {
    "id": 372204644,
    "name": "netbox-plugin-prometheus-sd",
    "full_name": "/FlxPeters/netbox-plugin-prometheus-sd",
    "owner": {
      "login": "FlxPeters",
      "id": 346241,
      "url": "https://github.com/FlxPeters",
      "type": "User"
    },
    "url": "https://github.com/FlxPeters/netbox-plugin-prometheus-sd",
    "description": "Provide Prometheus url_sd compatible API Endpoint with data from Netbox",
    "git_url": "git://github.com/FlxPeters/netbox-plugin-prometheus-sd.git",
    "clone_url": "https://github.com/FlxPeters/netbox-plugin-prometheus-sd.git",
    "created_at": "2021-05-30T12:09:10Z",
    "updated_at": "2022-03-10T22:27:03Z",
    "pushed_at": "2022-03-09T17:30:23Z",
    "stargazers_count": 30,
    "watchers_count": 30,
    "language": "Python",
    "forks": 5,
    "open_issues": 5,
    "topics": ["netbox-plugin", "prometheus"]
  },
  {
    "id": 252958798,
    "name": "netbox-vcenter",
    "full_name": "/sjm-steffann/netbox-vcenter",
    "owner": {
      "login": "sjm-steffann",
      "id": 13750942,
      "url": "https://github.com/sjm-steffann",
      "type": "Organization"
    },
    "url": "https://github.com/sjm-steffann/netbox-vcenter",
    "description": "vCenter integration plugin for NetBox",
    "git_url": "git://github.com/sjm-steffann/netbox-vcenter.git",
    "clone_url": "https://github.com/sjm-steffann/netbox-vcenter.git",
    "created_at": "2020-04-04T09:40:45Z",
    "updated_at": "2022-03-05T06:27:15Z",
    "pushed_at": "2020-12-14T20:47:50Z",
    "stargazers_count": 30,
    "watchers_count": 30,
    "language": "Python",
    "forks": 3,
    "open_issues": 1,
    "topics": ["netbox", "netbox-plugin", "vcenter"]
  },
  {
    "id": 320377683,
    "name": "ttl255-netbox-plugin-bgppeering",
    "full_name": "/progala/ttl255-netbox-plugin-bgppeering",
    "owner": {
      "login": "progala",
      "id": 27512690,
      "url": "https://github.com/progala",
      "type": "User"
    },
    "url": "https://github.com/progala/ttl255-netbox-plugin-bgppeering",
    "description": "Example NetBox plugin - Tracking BGP Peering connections",
    "git_url": "git://github.com/progala/ttl255-netbox-plugin-bgppeering.git",
    "clone_url": "https://github.com/progala/ttl255-netbox-plugin-bgppeering.git",
    "created_at": "2020-12-10T20:05:27Z",
    "updated_at": "2022-02-24T04:17:04Z",
    "pushed_at": "2021-03-08T21:10:23Z",
    "stargazers_count": 29,
    "watchers_count": 29,
    "language": "Python",
    "forks": 15,
    "open_issues": 3,
    "topics": ["netbox-plugin", "tutorial"]
  },
  {
    "id": 271839453,
    "name": "axians-netbox-plugin-pdu",
    "full_name": "/minitriga/axians-netbox-plugin-pdu",
    "owner": {
      "login": "minitriga",
      "id": 26367336,
      "url": "https://github.com/minitriga",
      "type": "User"
    },
    "url": "https://github.com/minitriga/axians-netbox-plugin-pdu",
    "description": "Netbox Plugin to Get PDU Information",
    "git_url": "git://github.com/minitriga/axians-netbox-plugin-pdu.git",
    "clone_url": "https://github.com/minitriga/axians-netbox-plugin-pdu.git",
    "created_at": "2020-06-12T16:09:10Z",
    "updated_at": "2022-02-18T11:53:38Z",
    "pushed_at": "2021-12-02T12:19:11Z",
    "stargazers_count": 27,
    "watchers_count": 27,
    "language": "Python",
    "forks": 7,
    "open_issues": 6,
    "topics": ["netbox-plugin"]
  },
  {
    "id": 281795478,
    "name": "ntc-netbox-plugin-metrics-ext",
    "full_name": "/networktocode/ntc-netbox-plugin-metrics-ext",
    "owner": {
      "login": "networktocode",
      "id": 13106404,
      "url": "https://github.com/networktocode",
      "type": "Organization"
    },
    "url": "https://github.com/networktocode/ntc-netbox-plugin-metrics-ext",
    "description": "NetBox Plugin to improve the instrumentation of NetBox and expose additional metrics (Application Metrics, RQ Worker).",
    "git_url": "git://github.com/networktocode/ntc-netbox-plugin-metrics-ext.git",
    "clone_url": "https://github.com/networktocode/ntc-netbox-plugin-metrics-ext.git",
    "created_at": "2020-07-22T22:27:08Z",
    "updated_at": "2021-12-11T22:08:32Z",
    "pushed_at": "2021-09-29T17:28:28Z",
    "stargazers_count": 25,
    "watchers_count": 25,
    "language": "Python",
    "forks": 6,
    "open_issues": 4,
    "topics": ["netbox", "netbox-plugin"]
  },
  {
    "id": 255680991,
    "name": "netbox-paloalto",
    "full_name": "/rodvand/netbox-paloalto",
    "owner": {
      "login": "rodvand",
      "id": 56864,
      "url": "https://github.com/rodvand",
      "type": "User"
    },
    "url": "https://github.com/rodvand/netbox-paloalto",
    "description": "NetBox plugin for listing firewall rules (from a Palo Alto Networks firewall/Panorama) associated with a NetBox object.",
    "git_url": "git://github.com/rodvand/netbox-paloalto.git",
    "clone_url": "https://github.com/rodvand/netbox-paloalto.git",
    "created_at": "2020-04-14T17:41:43Z",
    "updated_at": "2022-03-11T07:21:49Z",
    "pushed_at": "2021-02-28T19:48:13Z",
    "stargazers_count": 24,
    "watchers_count": 24,
    "language": "Python",
    "forks": 5,
    "open_issues": 7,
    "topics": ["netbox", "netbox-plugin", "palo-alto-networks"]
  },
  {
    "id": 282935033,
    "name": "netbox-nagios",
    "full_name": "/hudson-trading/netbox-nagios",
    "owner": {
      "login": "hudson-trading",
      "id": 40407330,
      "url": "https://github.com/hudson-trading",
      "type": "Organization"
    },
    "url": "https://github.com/hudson-trading/netbox-nagios",
    "description": "Plugin to show Nagios host and service status in NetBox on the device page.",
    "git_url": "git://github.com/hudson-trading/netbox-nagios.git",
    "clone_url": "https://github.com/hudson-trading/netbox-nagios.git",
    "created_at": "2020-07-27T15:15:07Z",
    "updated_at": "2022-02-02T19:52:23Z",
    "pushed_at": "2022-02-02T19:58:08Z",
    "stargazers_count": 23,
    "watchers_count": 23,
    "language": "Python",
    "forks": 7,
    "open_issues": 1,
    "topics": ["nagios", "netbox", "netbox-plugin"]
  },
  {
    "id": 265945466,
    "name": "netbox-tunnels-plugin",
    "full_name": "/jdrew82/netbox-tunnels-plugin",
    "owner": {
      "login": "jdrew82",
      "id": 2396364,
      "url": "https://github.com/jdrew82",
      "type": "User"
    },
    "url": "https://github.com/jdrew82/netbox-tunnels-plugin",
    "description": "Plugin for Netbox to support documentation of network tunneling protocols, ie VPNs, GRE, L2TP, etc.",
    "git_url": "git://github.com/jdrew82/netbox-tunnels-plugin.git",
    "clone_url": "https://github.com/jdrew82/netbox-tunnels-plugin.git",
    "created_at": "2020-05-21T20:30:22Z",
    "updated_at": "2022-03-11T17:12:32Z",
    "pushed_at": "2020-06-18T18:56:11Z",
    "stargazers_count": 22,
    "watchers_count": 22,
    "language": "Python",
    "forks": 4,
    "open_issues": 3,
    "topics": ["netbox", "netbox-plugin", "python"]
  },
  {
    "id": 369733751,
    "name": "netbox_capirca_plugin",
    "full_name": "/991jo/netbox_capirca_plugin",
    "owner": {
      "login": "991jo",
      "id": 1368323,
      "url": "https://github.com/991jo",
      "type": "User"
    },
    "url": "https://github.com/991jo/netbox_capirca_plugin",
    "description": "A Plugin to manage ACLs and Firewall rules with capirca inside NetBox.",
    "git_url": "git://github.com/991jo/netbox_capirca_plugin.git",
    "clone_url": "https://github.com/991jo/netbox_capirca_plugin.git",
    "created_at": "2021-05-22T06:30:25Z",
    "updated_at": "2022-02-07T13:31:54Z",
    "pushed_at": "2022-02-07T14:25:16Z",
    "stargazers_count": 17,
    "watchers_count": 17,
    "language": "Python",
    "forks": 0,
    "open_issues": 5,
    "topics": [
      "acl",
      "automation",
      "capirca",
      "firewall",
      "netbox",
      "netbox-plugin",
      "plugin"
    ]
  },
  {
    "id": 359814071,
    "name": "netbox-plugin-skeleton",
    "full_name": "/k01ek/netbox-plugin-skeleton",
    "owner": {
      "login": "k01ek",
      "id": 33313888,
      "url": "https://github.com/k01ek",
      "type": "User"
    },
    "url": "https://github.com/k01ek/netbox-plugin-skeleton",
    "description": "Skeleton for starting NetBox plugins",
    "git_url": "git://github.com/k01ek/netbox-plugin-skeleton.git",
    "clone_url": "https://github.com/k01ek/netbox-plugin-skeleton.git",
    "created_at": "2021-04-20T12:49:57Z",
    "updated_at": "2022-03-14T08:59:40Z",
    "pushed_at": "2022-03-10T01:37:06Z",
    "stargazers_count": 16,
    "watchers_count": 16,
    "language": "Python",
    "forks": 3,
    "open_issues": 2,
    "topics": ["netbox", "netbox-plugin", "python", "skeleton"]
  },
  {
    "id": 234575688,
    "name": "netbox-prometheus",
    "full_name": "/candlerb/netbox-prometheus",
    "owner": {
      "login": "candlerb",
      "id": 44789,
      "url": "https://github.com/candlerb",
      "type": "User"
    },
    "url": "https://github.com/candlerb/netbox-prometheus",
    "description": "Generate prometheus scrape targets and metadata from netbox",
    "git_url": "git://github.com/candlerb/netbox-prometheus.git",
    "clone_url": "https://github.com/candlerb/netbox-prometheus.git",
    "created_at": "2020-01-17T15:22:30Z",
    "updated_at": "2022-03-14T11:46:10Z",
    "pushed_at": "2021-09-20T12:34:36Z",
    "stargazers_count": 16,
    "watchers_count": 16,
    "language": "Python",
    "forks": 2,
    "open_issues": 1,
    "topics": ["netbox-api", "netbox-plugin"]
  },
  {
    "id": 359723875,
    "name": "netbox-plugin-interface-sync",
    "full_name": "/drygdryg/netbox-plugin-interface-sync",
    "owner": {
      "login": "drygdryg",
      "id": 43933400,
      "url": "https://github.com/drygdryg",
      "type": "User"
    },
    "url": "https://github.com/drygdryg/netbox-plugin-interface-sync",
    "description": "NetBox Plugin to compare and synchronize interfaces between devices and device types",
    "git_url": "git://github.com/drygdryg/netbox-plugin-interface-sync.git",
    "clone_url": "https://github.com/drygdryg/netbox-plugin-interface-sync.git",
    "created_at": "2021-04-20T07:28:50Z",
    "updated_at": "2022-01-23T17:49:10Z",
    "pushed_at": "2022-03-03T09:39:24Z",
    "stargazers_count": 15,
    "watchers_count": 15,
    "language": "Python",
    "forks": 1,
    "open_issues": 3,
    "topics": ["netbox", "netbox-plugin", "network-automation"]
  },
  {
    "id": 439228882,
    "name": "netbox-devicetype-importer",
    "full_name": "/k01ek/netbox-devicetype-importer",
    "owner": {
      "login": "k01ek",
      "id": 33313888,
      "url": "https://github.com/k01ek",
      "type": "User"
    },
    "url": "https://github.com/k01ek/netbox-devicetype-importer",
    "description": "Easy import DeviceTypes from github repo",
    "git_url": "git://github.com/k01ek/netbox-devicetype-importer.git",
    "clone_url": "https://github.com/k01ek/netbox-devicetype-importer.git",
    "created_at": "2021-12-17T06:09:01Z",
    "updated_at": "2022-03-11T17:14:26Z",
    "pushed_at": "2022-01-08T14:58:22Z",
    "stargazers_count": 14,
    "watchers_count": 14,
    "language": "Python",
    "forks": 0,
    "open_issues": 0,
    "topics": ["netbox", "netbox-plugin"]
  },
  {
    "id": 431599074,
    "name": "netbox-config-backup",
    "full_name": "/DanSheps/netbox-config-backup",
    "owner": {
      "login": "DanSheps",
      "id": 11049792,
      "url": "https://github.com/DanSheps",
      "type": "User"
    },
    "url": "https://github.com/DanSheps/netbox-config-backup",
    "description": "A configuration backup system using napalm",
    "git_url": "git://github.com/DanSheps/netbox-config-backup.git",
    "clone_url": "https://github.com/DanSheps/netbox-config-backup.git",
    "created_at": "2021-11-24T19:05:18Z",
    "updated_at": "2022-03-05T06:27:27Z",
    "pushed_at": "2022-01-12T14:55:05Z",
    "stargazers_count": 13,
    "watchers_count": 13,
    "language": "Python",
    "forks": 0,
    "open_issues": 1,
    "topics": ["netbox", "netbox-plugin"]
  },
  {
    "id": 331739828,
    "name": "ciscodnacnetbox",
    "full_name": "/robertcsapo/ciscodnacnetbox",
    "owner": {
      "login": "robertcsapo",
      "id": 11992244,
      "url": "https://github.com/robertcsapo",
      "type": "User"
    },
    "url": "https://github.com/robertcsapo/ciscodnacnetbox",
    "description": "Cisco DNA Center Integration with NetBox",
    "git_url": "git://github.com/robertcsapo/ciscodnacnetbox.git",
    "clone_url": "https://github.com/robertcsapo/ciscodnacnetbox.git",
    "created_at": "2021-01-21T19:59:43Z",
    "updated_at": "2022-02-18T00:37:01Z",
    "pushed_at": "2021-12-21T07:25:14Z",
    "stargazers_count": 12,
    "watchers_count": 12,
    "language": "Python",
    "forks": 5,
    "open_issues": 1,
    "topics": [
      "api",
      "cisco",
      "cisco-dna-center",
      "django",
      "netbox",
      "netbox-plugin",
      "netbox-script",
      "python"
    ]
  },
  {
    "id": 346165934,
    "name": "netbox-software-manager",
    "full_name": "/alsigna/netbox-software-manager",
    "owner": {
      "login": "alsigna",
      "id": 31988593,
      "url": "https://github.com/alsigna",
      "type": "User"
    },
    "url": "https://github.com/alsigna/netbox-software-manager",
    "description": "NetBox Plugin to deal with Cisco IOS & XE software",
    "git_url": "git://github.com/alsigna/netbox-software-manager.git",
    "clone_url": "https://github.com/alsigna/netbox-software-manager.git",
    "created_at": "2021-03-09T22:51:14Z",
    "updated_at": "2022-03-11T17:16:59Z",
    "pushed_at": "2021-04-18T00:00:18Z",
    "stargazers_count": 12,
    "watchers_count": 12,
    "language": "Python",
    "forks": 3,
    "open_issues": 2,
    "topics": ["netbox", "netbox-docker", "netbox-plugin"]
  },
  {
    "id": 411666583,
    "name": "netbox-cisco-support",
    "full_name": "/goebelmeier/netbox-cisco-support",
    "owner": {
      "login": "goebelmeier",
      "id": 1710701,
      "url": "https://github.com/goebelmeier",
      "type": "User"
    },
    "url": "https://github.com/goebelmeier/netbox-cisco-support",
    "description": "Implementing Cisco Support APIs into NetBox",
    "git_url": "git://github.com/goebelmeier/netbox-cisco-support.git",
    "clone_url": "https://github.com/goebelmeier/netbox-cisco-support.git",
    "created_at": "2021-09-29T12:32:20Z",
    "updated_at": "2022-03-14T19:29:26Z",
    "pushed_at": "2022-02-07T22:23:27Z",
    "stargazers_count": 12,
    "watchers_count": 12,
    "language": "Python",
    "forks": 4,
    "open_issues": 7,
    "topics": [
      "api",
      "cisco",
      "end-of-life",
      "netbox",
      "netbox-plugin",
      "support"
    ]
  }
]